#!/bin/zsh

# Add all folders in ~/.local/bin to path
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# DEFAULT APPLICATIONS
export BROWSER="firefox"
export EDITOR="nvim"
export TERMINAL="st"
export IMAGE_VIEWER="sxiv"
export DOCUMENT_VIEWER="zathura"

# DIRECTORIES
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export PICTURES="$HOME/pix"
export DOCUMENTS="$HOME/dox"
export MUSIC="$HOME/mus"
export VIDEOS="$HOME/vids"

export SCREENSHOTS="$PICTURES/shots"
export WALLPAPERS="$PICTURES/walls"
export MPDLIBRARY="$MUSIC/mpd"

export XNOTIFY_FIFO="$XDG_CACHE_HOME/xnotify.fifo"
export XRESOURCES="$XDG_CONFIG_HOME/x11/xresources"

# COMPOSE KEY
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus

# CLEANUP 
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export DVDCSS_CACHE="$XDG_DATA_HOME"/dvdcss
export HISTFILE=$HOME/.config/zsh/histfile
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export ANDROID_SDK_ROOT="${XDG_DATA_HOME:-$HOME/.local/share}/android"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export LESSHISTFILE="-"
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"

export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm

# Start x on tty1
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
