#!/bin/sh

# xinitrc runs automatically when you run startx.

# Run xprofile file
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ] && . "${XDG_CONFIG__HOME:-$HOME/.config}/x11/xprofile"

exec dwm
