#!/bin/sh

# xinitrc runs automatically when you run startx.

displays & # Set correct monitor layout and refresh rate
xrdb -load "$XRESOURCES" # Load Xresources
xsetroot -cursor_name left_ptr & # Change default cursor on desktop
setbg & # Set wallpaper, if pywal is installed it will override xresources
mpd-notification & # Notifications for mpd
unclutter & # Hide cursor if it is inactive
dwmblocks & # Update dwm status bar
dunst & # Start dunst notification daemon
xset r rate 300 50 & # Set keyboard rate higher
automail & # Script for automatic mail syncing, except when csgo is open.
gajim & # XMPP Messaging program

exec dwm # Launch dwm last
